Repository valkey-io/valkey-search, pull requests merged in 2025-09, with the labels that each got.

#392 Lexical Ordering for Keys in Postings KeyIterator
  src/indexes/text/posting.cc
  src/indexes/text/posting.h
  src/utils/string_interning.h
Labels: FT

#324 Add Text Properties to Schema Proto Reconstruction
  src/index_schema.cc
  src/index_schema.h
  src/index_schema.proto
  src/indexes/text.cc
  src/indexes/text/text_index.cc
  src/indexes/text/text_index.h
  testing/common.h
  testing/index_schema_test.cc
  testing/lexer_test.cc
  testing/radix_test.cc
  testing/text_index_schema_test.cc
  testing/text_test.cc
Labels: FT

#395 tag casesentive updated to be key-value pair
  src/indexes/tag.cc
  testing/ft_info_test.cc
Labels: needs-documentation

#337 Adding retry to fanout base class
  integration/test_fanout_base.py
  integration/test_info_cluster.py
  integration/test_info_primary.py
  src/commands/ft_info.cc
  src/coordinator/client.cc
  src/coordinator/coordinator.proto
  src/coordinator/info_converter.cc
  src/coordinator/info_converter.h
  src/coordinator/server.cc
  src/coordinator/server.h
  src/metrics.h
  src/query/cluster_info_fanout_operation.cc
  src/query/cluster_info_fanout_operation.h
  src/query/fanout_operation_base.h
  src/query/primary_info_fanout_operation.cc
  src/query/primary_info_fanout_operation.h
  src/valkey_search.cc
  src/valkey_search_options.cc
  src/valkey_search_options.h
  vmsdk/src/debug.cc
  vmsdk/src/debug.h
Labels: breaking-change

#327 Rough delete logic for the radix tree
  src/indexes/text/radix_tree.h
  testing/radix_test.cc
Labels: FT
